name: bib-api
dependencies:
- openssl=1.0.2d=0
- pip=7.1.2=py35_0
- python=3.5.1=0
- readline=6.2=2
- setuptools=19.1.1=py35_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - arrow==0.4.2
  - beautifulsoup4==4.3.2
  - bottle==0.12.8
  - gunicorn==19.3.0
  - ics==0.3.1
  - itsdangerous==0.24
  - marshmallow==1.2.6
  - python-dateutil==2.4.2
  - pytz==2015.4
  - redis==2.10.3
  - selenium==2.45.0
  - six==1.9.0

