name: bib-api
dependencies:
- libxml2=2.9.2=0
- libxslt=1.1.28=0
- lxml=3.6.0=py35_0
- openssl=1.0.2h=0
- pip=8.1.1=py35_1
- python=3.5.1=0
- readline=6.2=2
- setuptools=20.7.0=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - alabaster==0.7.7
  - arrow==0.4.2
  - babel==2.2.0
  - beautifulsoup4==4.4.1
  - bottle==0.12.8
  - docutils==0.12
  - flask==0.10.1
  - gunicorn==19.3.0
  - ics==0.3.1
  - itsdangerous==0.24
  - jinja2==2.8
  - markupsafe==0.23
  - marshmallow==1.2.6
  - py==1.4.31
  - pygments==2.0.2
  - pytest==2.8.5
  - python-dateutil==2.4.2
  - pytz==2015.4
  - redis==2.10.3
  - selenium==2.48.0
  - six==1.9.0
  - snowballstemmer==1.2.1
  - sphinx==1.3.4
  - sphinx-rtd-theme==0.1.9
  - sphinxcontrib-httpdomain==1.4.0
  - termcolor==1.1.0
  - werkzeug==0.11.10

