---
- name: install deps
  apt:
    pkg={{ item }}
    state=latest
  with_items:
    - git
    - libxml2-dev
    - libxslt1-dev
    - make
    - python3.5-dev
    - tree
    - zlib1g-dev

- name: install deps
  pip:
    name={{ item }}
    state=latest
  with_items:
    - flake8
    - tox

- stat: path=~/.batcave
  become: no
  register: batcave

- name: remove batcave
  become: no
  file:
    path=~/.batcave
    state=absent
  when: batcave.stat.exists

- name: clone batcave
  become: no
  git:
    repo=https://github.com/xsteadfastx/batcave.git
    dest=~/.batcave

- name: run batcave
  become: no
  command:
    ansible-playbook -i hosts shell.yml -c local --extra-vars="hosts=127.0.0.1"
    chdir=~/.batcave

- name: create virtualenv
  become: no
  pip:
    requirements=/vagrant/requirements.txt
    virtualenv=~/.virtualenvs/bib-api

- name: add env variables to xonshrc
  become: no
  lineinfile:
     line="{{ item }}"
     dest=~/.xonshrc
  with_items:
    - $REDIS_PORT_6379_TCP_ADDR = 'redis'
