---
- name: install deps
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - git
    - python3
    - ansible
    - redis-server
    - tree

- name: clone batcave
  become: no
  git:
    repo=https://github.com/xsteadfastx/batcave.git
    dest=~/batcave

- name: run batcave
  become: no
  command:
    ansible-playbook -i hosts base.yml -c local
    chdir=~/batcave

- name: create conda environment
  become: no
  command:
    ~/miniconda3/bin/conda env create --force
    chdir=/vagrant
