---
- name: download miniconda
  get_url:
    url=https://repo.continuum.io/miniconda/Miniconda3-3.19.0-Linux-x86.sh
    dest=/tmp/miniconda.sh
    mode=0755
    validate_certs=no
    checksum=md5:391bfdd892c2b8594b0d79bcfd2763c5

- name: install miniconda
  become: no
  shell: bash /tmp/miniconda.sh -b -f
  notify:
    - remove miniconda install script
